apiVersion: v1
kind: Secret
metadata:
  name: issuer-token-lmzpj
  namespace: wordpress
  annotations:
    kubernetes.io/service-account.name: sue-workshop-issuer
type: kubernetes.io/service-account-token
